[[redirects]]
    from = '/api/*'
    to = '/.netlify/functions/api/:splat'
    status = 200

[functions]
    node_bundler = 'esbuild'

[[plugins]]
  package = "netlify-plugin-cloudinary"

[plugins.inputs]
  cloudName = "dknctjjlc"